# pre-commit stop running hooks after the first failure.
fail_fast: true
# A list of repository mappings
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # Remove spaces at end of lines except markdown
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: '(\.obsidian)/.*'
      # Make the last line of the file a newline code
      - id: end-of-file-fixer
        exclude: '(\.obsidian)/.*'
        # Unify line break code to LF
      - id: mixed-line-ending
        args: [--fix=lf]
        exclude: '(\.obsidian/.*)'
      # toml syntax check
      - id: check-toml
      # yaml syntax check
      - id: check-yaml
        # Exclude check for "could not determine a constructor for the tag 'tag:yaml.org,2002:python/name:materialx.emoji.twemoji'"
        args: [--unsafe]

  # https://github.com/astral-sh/uv-pre-commit
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.5
    hooks:
      - id: uv-lock
        verbose: true

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.16.4
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.3.1
    hooks:
      - id: mypy
        additional_dependencies: [types-requests==2.32.0.20240622]
        args: [--config-file=pyproject.toml]
        exclude: ^docs/gist/
